# @package _global_

model:
  _target_: models.arch.bihalf.BiHalf
  gamma: 6.0
  backbone: ${backbone}
  nbit: 64
  nclass: ${dataset.nclass}

trainer:
  _target_: trainers.bihalf.BiHalfTrainer

criterion:
  _target_: models.loss.bihalf.BiHalfLoss