# @package _global_
defaults:
  - override /transforms: cibhash
  - override /backbone: vgg16
  - _self_


model:
  _target_: models.arch.cibhash.CIBHash
  backbone: ${backbone}
  nbit: 64
  nclass: ${dataset.nclass}

trainer:
  _target_: trainers.cibhash.CIBHashTrainer

criterion:
  _target_: models.loss.cibhash.CIBHashLoss
  multiclass: ${dataset.multiclass}
  beta: 0.001
  temperature: 0.3

