# @package _global_
defaults:
  - override /transforms: cibhash
  - _self_

model:
  _target_: models.arch.sdc.SDC
  backbone: ${backbone}
  nbit: 64
  nclass: ${dataset.nclass}

trainer:
  _target_: trainers.sdc.SDCTrainer

criterion:
  _target_: models.loss.sdc.SDCLoss
  rec: 1
  rec_type: "l1"
  quan: 1
  quan_type: "cs"
  beta_ab: 5
  ortho_constraint: True
  cont: 1
  contrastive:
    _target_: models.loss.simclr.SimCLRLoss
    temperature: 0.3

backbone_lr_scale: 0