# @package _global_

dataset:
  train_dataset:
    transform:
      - _target_: utils.transforms.NCropsTransform
        _args_:
          - _target_: torchvision.transforms.Compose
            transforms:
              - _target_: torchvision.transforms.RandomResizedCrop
                scale: [ 0.2, 1.0 ]
                size: ${dataset.crop}
              - _target_: torchvision.transforms.RandomHorizontalFlip
              - _target_: torchvision.transforms.RandomApply
                _args_:
                  - - _target_: torchvision.transforms.ColorJitter
                      _args_: [ 0.4, 0.4, 0.4, 0.1 ]
                p: 0.8
              - _target_: torchvision.transforms.RandomGrayscale
                p: 0.2
              - _target_: utils.transforms.GaussianBlur
                sigma: [ 0.1, 2.0 ]
              - _target_: torchvision.transforms.ToTensor
              - _target_: utils.transforms.normalize_transform
                norm: 2
          - _target_: torchvision.transforms.Compose
            transforms:
              - _target_: torchvision.transforms.RandomResizedCrop
                scale: [ 0.2, 1.0 ]
                size: ${dataset.crop}
              - _target_: torchvision.transforms.RandomHorizontalFlip
              - _target_: torchvision.transforms.ColorJitter
                _args_: [ 0.4, 0.4, 0.4, 0.4 ]
              - _target_: torchvision.transforms.RandomGrayscale
                p: 0.2
              - _target_: torchvision.transforms.ToTensor
              - _target_: utils.transforms.normalize_transform
                norm: 2